Update Packages-AutoBuild.yml

diff --git a/.github/workflows/Packages-AutoBuild.yml b/.github/workflows/Packages-AutoBuild.yml
--- a/.github/workflows/Packages-AutoBuild.yml
+++ b/.github/workflows/Packages-AutoBuild.yml
@@ -66,7 +66,7 @@ jobs:
 
     - name: Free disk space
       uses: coder-xiaomo/free-disk-space@main
-      if: contains(github.event.action, 'a-')
+      if: contains(github.event.action, 'all') || contains(github.event.action, 'lang')
       with:
         tool-cache: false
         android: true
@@ -84,7 +84,7 @@ jobs:
         sudo -E apt-get -qq install build-essential libncurses-dev zlib1g-dev gawk git \
         gettext libssl-dev xsltproc rsync wget unzip \
         llvm python3-pyelftools libpython3-dev aria2 jq qemu-utils rename \
-        libelf-dev libgmp3-dev libmpc-dev libfuse-dev bc autopoint cups-ppdc upx
+        libelf-dev libgmp3-dev libmpc-dev libfuse-dev bc autopoint upx
         sudo -E apt-get -qq autoremove --purge
         sudo -E apt-get -qq clean
         sudo timedatectl set-timezone "Asia/Shanghai"
@@ -150,7 +150,7 @@ jobs:
           cd $rootdir
           }
         export -f git_clone_path
-        tar -xJf sdk.tar.zst -C openwrt || tar -xf sdk.tar.zst -C openwrt
+        tar -xf sdk.tar.zst -C openwrt
         cd openwrt
         cp -rf ./openwrt-sdk*/. ./ 2>/dev/null || true
         cp -rf ./openwrt-sdk*/build_dir/. ./build_dir/ || true
@@ -189,34 +189,28 @@ jobs:
       run: |
         cd openwrt
         mv -f package/feeds/miaogongzi miaogongzi.b
-        mv -f feeds/packages feeds/packages.b
         mkdir package/feeds/miaogongzi
-        cp -rf miaogongzi.b/{wxbase,lib*,rapidjson,nftables,jpcre2,toml11,gn,curl,quickjspp,qt*,libdouble*,libtorrent*,openssl,mbedtls,ppp,cups,nftables} package/feeds/miaogongzi/ || true
+        mv -f miaogongzi.b/{wxbase,lib*,rapidjson,jpcre2,toml11,gn,quickjspp,qt*,libdouble*} package/feeds/miaogongzi/ || true
 
     - name: Compile the firmware
       run: |
         cd openwrt
           echo -e "$(($(nproc)+1)) thread compile"
-          fpkg="$(echo "${{github.event.action}}" | sed -e 's/\(aarch64_generic\|x86_64\|i386_pentium4\|arm_arm1176jzf-s_vfp\|aarch64_cortex-a72\|aarch64_cortex-a76\|arm_cortex-a7\|arm_cortex-a7_neon-vfpv4\|arm_cortex-a9\|arm_cortex-a15_neon-vfpv4\|arm_cortex-a5_vfpv4\|mipsel_24kc\|mips_24kc\|aarch64_cortex-a53\|arm_xscale\|arm_cortex-a9_vfpv3-d16\|riscv64_generic\| [0-9][0-9.]*\| ssh\| noser\| cw\)//g' | sed -e 's/ //g')"
+          fpkg="$(echo "${{github.event.action}}" | sed -e 's/\(aarch64_generic\|x86_64\|i386_pentium4\|arm_arm1176jzf-s_vfp\|aarch64_cortex-a72\|aarch64_cortex-a76\|arm_cortex-a7\|arm_cortex-a7_neon-vfpv4\|arm_cortex-a9\|arm_cortex-a15_neon-vfpv4\|arm_cortex-a5_vfpv4\|mipsel_24kc\|mips_24kc\|aarch64_cortex-a53\|arm_xscale\|arm_cortex-a9_vfpv3-d16\|riscv64_generic\| [0-9][0-9.]*\| ssh\| noser\| cw\| all\| lang\)//g' | sed -e 's/ //g')"
           echo "FPKG=$fpkg" >> $GITHUB_ENV
           during="$(echo "${{github.event.action}}" | grep -o -E ' [0-9][0-9.]*' | sed -e 's/ //')"
           function comp(){
              echo "compile $ipk"
-             cp -rf miaogongzi.b/$ipk package/feeds/miaogongzi/
-             if [[ $ipk != luci-* ]]; then
-              mv -f feeds/packages.b feeds/packages
-              [ "$(grep "PKG_BUILD_DEPENDS" package/feeds/miaogongzi/$ipk/Makefile)" ] || mv feeds/packages/lang/node feeds/packages/lang/node.b
-             fi
-             (make -k package/$ipk/compile -j$(($(nproc)+1)) || make package/$ipk/compile V=s 2>&1 | tee error_$ipk.log | grep -i "Error 2" || rm -rf error_$ipk.log) || true
-             if [[ $ipk != luci-* ]]; then
-              mv -f feeds/packages/lang/node.b feeds/packages/lang/node 2>/dev/null || true
-              mv -f feeds/packages feeds/packages.b
-              rm -rf package/feeds/miaogongzi/$ipk
-             fi
+             cp -rf miaogongzi.b/$ipk* package/feeds/miaogongzi/
+             make -k package/$ipk/compile -j$(($(nproc)+1)) || (make -k package/$ipk/compile V=s 2>&1 | tee error_$ipk.log | grep -i "Error 2" || true)
+             rm -rf package/feeds/miaogongzi/$ipk*
             }
           for ipk in $(ls miaogongzi.b | grep -E "$fpkg"); do
-            echo $ipk
-            if [[ "$fpkg" && ! "$during" ]]; then
+            if [ "$(echo "${{ github.event.action }}" | grep "lang")" ];then
+              [ "$(grep -E '(golang|node|rust)' feeds/miaogongzi/$ipk/Makefile)" ] && comp
+            elif [ "$(echo "${{ github.event.action }}" | grep "all")" ];then
+              [ ! "$(grep -E '(golang|node|rust)' feeds/miaogongzi/$ipk/Makefile)" ] && comp
+            elif [[ "$fpkg" && ! "$during" ]]; then
               comp
             else
               REPO_TOKEN="${{ env.REPO_TOKEN }}"
@@ -256,12 +250,9 @@ jobs:
     - name: Organize files
       id: organize
       run: |
-        mkdir packages
-        [[ "$(echo "${{github.event.action}}" | grep "a-")" ]] ||
-          mv -f openwrt/bin/packages/*/miaogongzi/* packages || true
-        mv -f openwrt/.config packages/${{matrix.target}}.config || true
-        # cp -Rf openwrt/bin/packages/*/packages/python3* packages/
-        # cp -Rf openwrt/bin/packages/*/luci/luci-base* packages/ || true
+        mv -f openwrt/.config openwrt/bin/packages/*/miaogongzi/ || true
+        echo "${{ github.event.action }}" | grep -E -qv '(all|lang)' && PACKAGES="openwrt/bin/packages/*/miaogongzi/*"
+        echo "PACKAGES=$PACKAGES" >> $GITHUB_ENV
         echo "FIRMWARE=$PWD/packages" >> $GITHUB_ENV
         Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🛸" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
         echo "EMOJI=${Emoji[$[$RANDOM % ${#Emoji[@]}]]}" >> $GITHUB_ENV
@@ -270,26 +261,6 @@ jobs:
         else
            echo "NAME=❌ ${{ env.date2 }} ${{matrix.target}} ❌" >> $GITHUB_ENV
         fi
-
-    - name: Upload firmware to cowtransfer
-      if: env.UPLOAD_FIRMWARE_TO_COWTRANSFER == 'true'
-      continue-on-error: true
-      run: |
-        curl -fsSL git.io/file-transfer | sh
-        cowurl=$(./transfer cow --block 2621440 -s --no-progress ${FIRMWARE})
-        cowurl=$(echo $cowurl | grep -o -E "https[^ ]*")
-        echo "COWURL=$cowurl" >> $GITHUB_ENV
-        echo "Download Link: ${{ env.EMOJI }} $cowurl ${{ env.EMOJI }} 🚀"
- 
-    - name: Upload firmware to WeTransfer
-      if: env.UPLOAD_FIRMWARE_TO_WETRANSFER == 'true'
-      continue-on-error: true
-      run: |
-        curl -fsSL git.io/file-transfer | sh
-        wetrans=$(./transfer wet -s -p 16 --no-progress ${FIRMWARE})
-        wetrans=$(echo $wetrans | grep -o -E "https[^ ]*")
-        echo "WETRANS=$wetrans" >> $GITHUB_ENV
-        echo "Download Link: ${{ env.EMOJI }} $wetrans ${{ env.EMOJI }} 🚀"
         
     - name: Create release
       id: create_release
@@ -297,10 +268,7 @@ jobs:
       continue-on-error: true
       run: |
         echo -e "墙内加速下载 🚀:\n" >> release.txt
-        echo -e "[阿里云] (https://op.miaogongzi.cc/23.05/packages/${{matrix.target}}/ ☁)\n" >> release.txt
-        [ ${{ env.WETRANS }} ] && echo -e "[WeTransfer] (${{ env.WETRANS }} 🗽)\n" >> release.txt
-        [ ${{ env.COWURL }} ] && echo -e "[奶牛上传] (${{ env.COWURL }} 🐮)\n" >> release.txt
-        [ ${{ env.NOTICE }} ] && echo -e "${{ env.NOTICE }}" >> release.txt || true
+        echo -e "https://op.miaogongzi.cc/23.05/packages/${{matrix.target}}/ ☁)\n" >> release.txt
 
     - name: Upload packages for release
       uses: softprops/action-gh-release@master
@@ -310,8 +278,8 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.TOKEN_MGZ0227 }}
       with:
         files: |
-            packages/*
             openwrt/error*.log
+            ${{ env.PACKAGES }}
         name: ${{ env.NAME }}
         tag_name: ${{ env.date }}_${{matrix.target}}
         body_path: release.txt
@@ -323,7 +291,7 @@ jobs:
       with:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         ARGS: "-avr --timeout=600"
-        SOURCE: "packages/"
+        SOURCE: "openwrt/bin/packages/*/miaogongzi/"
         REMOTE_HOST: ${{ secrets.HOST }}
         REMOTE_PORT: ${{ secrets.PORT }}
         REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
@@ -337,8 +305,8 @@ jobs:
       with:
         SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
         ARGS: "-avr --timeout=600"
-        SSH_CMD_ARGS: "-o ServerAliveInterval=30 -o ServerAliveCountMax=10"
-        SOURCE: "packages/"
+        SSH_CMD_ARGS: "-o ServerAliveInterval=30 -o ServerAliveCountMax=10 -o StrictHostKeyChecking=no"
+        SOURCE: "openwrt/bin/packages/*/miaogongzi/"
         REMOTE_HOST: ${{ secrets.SERVER_HOST }}
         REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
         REMOTE_PORT: ${{ secrets.SERVER_PORT }}
